@echo off
echo Criando ambiente virtual...
python -m venv venv
call venv\Scripts\activate.bat
echo Atualizando pip, setuptools e wheel...
python -m pip install --upgrade pip setuptools wheel
echo Instalando dependencias...
pip install -r requirements.txt
echo Executando o aplicativo...
python main.py
pause
